/* 
 * Copyright (C) 2017 by Fonoster Inc (http://fonoster.com)
 * http://astivetoolkit.org
 *
 * This file is part of Astive Toolkit(ATK)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.astivetoolkit.agi;


/**
 * Thrown by AGI protocol(e.g. I/O operation issues or
 * malformed commands).
 *
 * @since 1.0
 */
public class AgiException extends Exception {
  private static final long serialVersionUID = 1104077605229857235L;

  /**
   * Create a new AgiException object.
   */
  public AgiException() {
  }

  /**
   * Create a new AgiException object with message.
   *
   * @param msg information generated by the exception.
   */
  public AgiException(String msg) {
    super(msg);
  }

  /**
   * Creates a new AgiException object.
   *
   * @param e original exception.
   */
  public AgiException(Exception e) {
    super(e);
  }
}
