#!/bin/sh

# Copyright (C) 2017 by Fonoster Inc (http://fonoster.com)
# http://astivetoolkit.org
#
# This file is part of Astive Toolkit(ATK)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Remove comment to generate javadocs
#OPTIONS="javadoc:aggregate"

# Remove comment to format using Jalopy
#OPTIONS="$OPTIONS jalopy:format"

# Remove comment to include Unit Tests
#OPTIONS="$OPTIONS -DskipTests=false"

command -v java >/dev/null 2>&1 || { echo "I require Java but it's not installed. Aborting." >&2; exit 1; }

# Maven is require to compile ATK
command -v mvn >/dev/null 2>&1 || { echo "I require Maven but it's not installed. Aborting." >&2; exit 1; }

echo "\nPlease wait, this may take few minutes...\n"

mvn -q install assembly:assembly -DskipTests=true $OPTIONS

if [ $? = 0 ]; then
    echo " * Congratulations, you have assembled a new astive-server and astive-sdk"	
    echo " * Your assemblies can be found in folder 'dist'."
else
    echo " * Something when wrong with ATK."
fi

echo "\nHome Page: http://astivetoolkit.org"
echo "Report bugs to: dev@astivetoolkit.org"

